[theme]
base                            = "light"
primaryColor                    = "#0D9488"
backgroundColor                 = "#FFFFFF"
secondaryBackgroundColor        = "#F1F5F9"
textColor                       = "#0F172A"
borderColor                     = "#E2E8F0"
dataframeBorderColor            = "#E2E8F0"
dataframeHeaderBackgroundColor  = "#F8FAFC"
baseRadius                      = "2rem"
buttonRadius                    = "2rem"
font                            = "DM Sans, sans-serif"
fontFaces                       = [{family = "DM Sans", url = "https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,300..700;1,9..40,300..700&display=swap"}]
